### ISSUE TITLE
about the performance

### ISSUE THREAD

**Issue by lawpdas** [zllrunning/SiameseX.PyTorch#1]
Have you tested the performance of SiamRPN?

**Comment by whjzsy** [comment]
您好，在用您的代码训练时，遇到
![QQ截图20190423184121](https://user-images.githubusercontent.com/28587699/56575097-7b366280-65f7-11e9-9949-dffb472f3852.png)，能帮忙看看是什么原因吗？

**Comment by zllrunning** [comment]
Sorry, I haven't done this yet.

**Comment by fAnchao1** [comment]
have you tested the accuarcy of siamfc on otb100?

**Comment by fAnchao1** [comment]
@zllrunning

**Comment by zllrunning** [comment]
Not yet. Training and evaluation are still under development.
