### ISSUE TITLE
where is ilsvrc_vid.txt?

### ISSUE THREAD

**Issue by LpfML** [zllrunning/SiameseX.PyTorch#2]
I download the ilsvrc_vid2015 Dataset， but i can't find ilsvrc_vid.txt  can you  help me?

**Comment by zllrunning** [comment]
You can download it from [here](https://drive.google.com/open?id=13aC_2stCEU0VoiIpp6wgudenUSVye74b).

**Comment by LpfML** [comment]
thank you so much.
