### ISSUE TITLE
how to solve it?

### ISSUE THREAD

**Issue by zlb2016** [zllrunning/SiameseX.PyTorch#4]
when i excute the second command: python demo.py --model SiamFC
something is wrong like:

![2019-05-01 15-40-12屏幕截图](https://user-images.githubusercontent.com/38319840/57009161-8573e480-6c27-11e9-9bc0-06f25243c952.png)

**Comment by Totoro-wen** [comment]
Hello, I have the same problem, how do you solve it.

**Comment by zllrunning** [comment]
Because I didn't upload the pretrained model of SiamFC, I will upload it recently.
