### ISSUE TITLE
Any plans for the cfnet?

### ISSUE THREAD

**Issue by iminfine** [zllrunning/SiameseX.PyTorch#5]
Thanks for your nice work! It helps me a lot.

Are there plans for the cfnet, the siamfc-v2? I notice that there is not a Tensorflow or Pytorch version thus making it helpful if one did it. 

Besides, I read your to-do lists and guess you are working for testing trackers on common datasets. GOT-10k toolkit is a useful tool for this, just a small suggestion.

**Comment by zllrunning** [comment]
I haven't considered the implementation of CFNet yet, I might consider it later. In addition, thank you for your suggestion.

**Comment by zllrunning** [comment]
I haven't considered the implementation of CFNET yet, I might consider it later. In addition, thanks for your suggestion.
